[profile.default]
retries = { backoff = "fixed", count = 3, delay = "3s" }

[profile.ci]
retries = { backoff = "fixed", count = 3, delay = "3s" }
threads-required = 1
test-threads = 1
fail-fast = false
failure-output = "immediate-final"
slow-timeout = { period = "30s", terminate-after = 4 }

